### ISSUE TITLE
Crashes when git log is too long

### ISSUE THREAD

**Issue by brownzach125** [simonrenoult/git-log-to-json#2]
There should be a way to use the -n flag for git log

**Comment by simonrenoult** [comment]
Hi,

Sorry for the very late response. How many commits have you tried? The `-n` flag is a good idea. I'll look into it.

**Comment by simonrenoult** [comment]
I added a new param `--limit` (or `-L`) in https://github.com/simonrenoult/git-log-to-json/releases/tag/v1.1.1
